nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/containers/envFrom/configMapRef/name
  - kind: Secret
    version: v1
    fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/containers/envFrom/secretRef/name
varReference:
  - path: data
    kind: ConfigMap
