apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/getupnet/auth-service:release
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
spec:
  template:
    spec:
      containers:
        - name: billing
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/getupnet/billing-service:release
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
spec:
  template:
    spec:
      containers:
        - name: client
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/getupnet/client-service:release
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sign-service
spec:
  template:
    spec:
      containers:
        - name: sign
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/getupnet/sign-service:release
