apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: billing-service
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: billing-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sign-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sign-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker-service
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: worker-service
