apiVersion: apps/v1
kind: Deployment
metadata:
  name: getupnet-api
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: api
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/getupnet-api:staging
          env:
            - name: ENVIRONMENT
              value: staging
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "750m"
              memory: "1024Mi"
