apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: getupnet-api
  labels:
    app.kubernetes.io/name: getupnet-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: getupnet-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Pods
      pods:
        metric:
          name: http_request_duration_seconds_p95
        target:
          type: AverageValue
          averageValue: 500m
