name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - name: Ejecutar pruebas
        run: |
          pytest --maxfail=1 --disable-warnings -q
