name: Frontend CI

on:
  push:
    branches: [main, develop]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"
  pull_request:
    paths:
      - "frontend/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: frontend
        run: pnpm install --frozen-lockfile
      - name: Type check
        working-directory: frontend
        run: pnpm lint
      - name: Build admin portal
        working-directory: frontend
        run: pnpm --filter @getupnet/admin-portal build
      - name: Build client portal
        working-directory: frontend
        run: pnpm --filter @getupnet/client-portal build
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: |
            frontend/apps/admin-portal/dist
            frontend/apps/client-portal/dist
